import type { Alert } from "@/lib/types";
import { PLANTS } from "@/lib/mock-data/plants";

const PLANT_NAMES = Object.fromEntries(
  PLANTS.map((plant) => [plant.id, plant.name]),
) as Record<string, string>;

const OXFORD = PLANT_NAMES["plant-1"];
const WARREN = PLANT_NAMES["plant-2"];
const LANSING = PLANT_NAMES["plant-3"];
const DETROIT = PLANT_NAMES["plant-4"];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alert-plant-2-scrap",
    severity: "critical",
    status: "open",
    plantId: "plant-2",
    plantName: WARREN,
    metric: "scrapRate",
    title: "Seat trim scrap exceeded the rolling quality baseline",
    summary:
      `${WARREN} scrap has climbed for seven consecutive days and now sits materially above its recent operating band on the truck-seat build.`,
    detectedAt: "2026-04-15T09:24:00Z",
    changeVsBaseline: 0.014,
    drivers: [
      "Tool wear on trim Line 4",
      "Rework loop time is climbing",
      "Second-shift overtime on seat assembly",
    ],
    sources: ["MES", "CMMS"],
    chartPoints: [
      { label: "Apr 11", value: 0.05, baseline: 0.041 },
      { label: "Apr 12", value: 0.051, baseline: 0.041 },
      { label: "Apr 13", value: 0.053, baseline: 0.042 },
      { label: "Apr 14", value: 0.054, baseline: 0.042 },
      { label: "Apr 15", value: 0.056, baseline: 0.042 },
    ],
  },
  {
    id: "alert-plant-2-inventory",
    severity: "medium",
    status: "open",
    plantId: "plant-2",
    plantName: WARREN,
    metric: "inventoryHealth",
    title: "Critical trim coverage is slipping below the safe buffer",
    summary:
      `${WARREN} still shows enough inventory on paper, but unstable scrap consumption is draining high-risk foam and trim material faster than planned.`,
    detectedAt: "2026-04-15T09:01:00Z",
    changeVsBaseline: -0.05,
    drivers: [
      "Scrap burn on Line 4",
      "Late trim replenishment",
      "Short-term sequencing overrides",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 11", value: 0.79, baseline: 0.83 },
      { label: "Apr 12", value: 0.78, baseline: 0.83 },
      { label: "Apr 13", value: 0.77, baseline: 0.82 },
      { label: "Apr 14", value: 0.77, baseline: 0.82 },
      { label: "Apr 15", value: 0.76, baseline: 0.81 },
    ],
  },
  {
    id: "alert-plant-2-downtime",
    severity: "high",
    status: "open",
    plantId: "plant-2",
    plantName: WARREN,
    metric: "downtime",
    title: "Downtime escalation is now concentrated in maintenance and tooling",
    summary:
      `Downtime minutes continue to rise in ${WARREN}, making it the biggest contributor to the current network OEE decline.`,
    detectedAt: "2026-04-15T08:52:00Z",
    changeVsBaseline: 24,
    drivers: [
      "Maintenance queue backlog",
      "Unplanned trim-tool replacement",
      "Extended changeovers after quality holds",
    ],
    sources: ["CMMS", "MES"],
    chartPoints: [
      { label: "Apr 11", value: 126, baseline: 108 },
      { label: "Apr 12", value: 129, baseline: 108 },
      { label: "Apr 13", value: 133, baseline: 109 },
      { label: "Apr 14", value: 137, baseline: 109 },
      { label: "Apr 15", value: 141, baseline: 110 },
    ],
  },
  {
    id: "alert-plant-3-otif",
    severity: "high",
    status: "watch",
    plantId: "plant-3",
    plantName: LANSING,
    metric: "otif",
    title: "OTIF is softening despite strong production performance",
    summary:
      `${LANSING} output remains healthy, but outbound service has slipped as staging and packaging queues tighten.`,
    detectedAt: "2026-04-15T07:15:00Z",
    changeVsBaseline: -0.04,
    drivers: [
      "Trailer staging congestion",
      "Late packaging confirmations",
      "Expedite mix pressure",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 11", value: 0.92, baseline: 0.95 },
      { label: "Apr 12", value: 0.92, baseline: 0.95 },
      { label: "Apr 13", value: 0.91, baseline: 0.95 },
      { label: "Apr 14", value: 0.91, baseline: 0.95 },
      { label: "Apr 15", value: 0.9, baseline: 0.95 },
    ],
  },
  {
    id: "alert-plant-3-packaging",
    severity: "medium",
    status: "watch",
    plantId: "plant-3",
    plantName: LANSING,
    metric: "downtime",
    title: "Packaging verification delays are starting to erode outbound flow",
    summary:
      `${LANSING} line performance remains strong overall, but repeated verification and staging interruptions are now feeding the OTIF slowdown.`,
    detectedAt: "2026-04-15T07:02:00Z",
    changeVsBaseline: 9,
    drivers: [
      "Verification resets on Pack Line 2",
      "Late changeover signoff",
      "Accumulation lane congestion",
    ],
    sources: ["MES", "CMMS"],
    chartPoints: [
      { label: "Apr 11", value: 61, baseline: 56 },
      { label: "Apr 12", value: 62, baseline: 56 },
      { label: "Apr 13", value: 63, baseline: 56 },
      { label: "Apr 14", value: 61, baseline: 56 },
      { label: "Apr 15", value: 60, baseline: 56 },
    ],
  },
  {
    id: "alert-plant-4-inventory",
    severity: "medium",
    status: "watch",
    plantId: "plant-4",
    plantName: DETROIT,
    metric: "inventoryHealth",
    title: "Inventory imbalance is creating localized kit shortages",
    summary:
      `${DETROIT} still has enough inventory overall, but coverage is mismatched across critical seat and interior assemblies.`,
    detectedAt: "2026-04-15T06:40:00Z",
    changeVsBaseline: -0.06,
    drivers: [
      "Uneven replenishment timing",
      "Component mix skew",
      "Slow transfer approvals",
    ],
    sources: ["ERP"],
    chartPoints: [
      { label: "Apr 11", value: 0.74, baseline: 0.79 },
      { label: "Apr 12", value: 0.73, baseline: 0.79 },
      { label: "Apr 13", value: 0.72, baseline: 0.79 },
      { label: "Apr 14", value: 0.72, baseline: 0.79 },
      { label: "Apr 15", value: 0.71, baseline: 0.79 },
    ],
  },
  {
    id: "alert-plant-4-downtime",
    severity: "medium",
    status: "watch",
    plantId: "plant-4",
    plantName: DETROIT,
    metric: "downtime",
    title: "Changeover drag is extending Detroit final assembly windows",
    summary:
      `${DETROIT} downtime is not spiking into crisis territory, but changeover drag is stacking on top of inventory friction and slowing schedule recovery.`,
    detectedAt: "2026-04-15T06:18:00Z",
    changeVsBaseline: 8,
    drivers: [
      "Mixed-model sequencing",
      "Late kit substitutions",
      "Supervisor approvals after holds",
    ],
    sources: ["MES", "CMMS"],
    chartPoints: [
      { label: "Apr 11", value: 95, baseline: 89 },
      { label: "Apr 12", value: 97, baseline: 89 },
      { label: "Apr 13", value: 98, baseline: 90 },
      { label: "Apr 14", value: 96, baseline: 90 },
      { label: "Apr 15", value: 97, baseline: 90 },
    ],
  },
  {
    id: "alert-plant-1-watch",
    severity: "low",
    status: "watch",
    plantId: "plant-1",
    plantName: OXFORD,
    metric: "downtime",
    title: "Minor trim changeover variability is worth monitoring",
    summary:
      `${OXFORD} remains healthy overall, though changeover minutes ticked up enough to keep a low-severity watch open.`,
    detectedAt: "2026-04-15T05:32:00Z",
    changeVsBaseline: 5,
    drivers: ["Product-family mix shift", "New operator rotation"],
    sources: ["MES"],
    chartPoints: [
      { label: "Apr 11", value: 72, baseline: 68 },
      { label: "Apr 12", value: 74, baseline: 68 },
      { label: "Apr 13", value: 70, baseline: 68 },
      { label: "Apr 14", value: 68, baseline: 68 },
      { label: "Apr 15", value: 69, baseline: 68 },
    ],
  },
  {
    id: "alert-plant-1-otif",
    severity: "low",
    status: "watch",
    plantId: "plant-1",
    plantName: OXFORD,
    metric: "otif",
    title: "A small pocket of expedite sequenced orders slipped late",
    summary:
      `${OXFORD} remains the benchmark site, but two expedite seat sets missed the normal outbound window after a short-term product mix shift.`,
    detectedAt: "2026-04-15T05:11:00Z",
    changeVsBaseline: -0.01,
    drivers: [
      "Short-term product mix swing",
      "New outbound coordinator rotation",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 11", value: 0.95, baseline: 0.96 },
      { label: "Apr 12", value: 0.95, baseline: 0.96 },
      { label: "Apr 13", value: 0.95, baseline: 0.96 },
      { label: "Apr 14", value: 0.95, baseline: 0.96 },
      { label: "Apr 15", value: 0.96, baseline: 0.96 },
    ],
  },
  {
    id: "alert-plant-3-scrap-resolved",
    severity: "low",
    status: "resolved",
    plantId: "plant-3",
    plantName: LANSING,
    metric: "scrapRate",
    title: "Surface-finish scrap spike has returned to normal range",
    summary:
      `A short-lived finish defect spike earlier in the week was contained, and scrap has moved back into ${LANSING}'s expected operating band.`,
    detectedAt: "2026-04-14T17:08:00Z",
    changeVsBaseline: -0.002,
    drivers: [
      "Coating temperature correction",
      "Hold-and-release review completed",
    ],
    sources: ["MES"],
    chartPoints: [
      { label: "Apr 10", value: 0.028, baseline: 0.028 },
      { label: "Apr 11", value: 0.027, baseline: 0.028 },
      { label: "Apr 12", value: 0.026, baseline: 0.028 },
      { label: "Apr 13", value: 0.026, baseline: 0.028 },
      { label: "Apr 14", value: 0.026, baseline: 0.028 },
    ],
  },
  {
    id: "alert-plant-4-kit-shortage",
    severity: "critical",
    status: "open",
    plantId: "plant-4",
    plantName: DETROIT,
    metric: "inventoryHealth",
    title: "Localized seat kit shortages crossed the recovery threshold",
    summary:
      `${DETROIT} had enough total inventory on hand yesterday, but repeated allocation misses on two final-assembly families forced recovery-level kit intervention.`,
    detectedAt: "2026-04-14T18:46:00Z",
    changeVsBaseline: -0.09,
    drivers: [
      "Seat kit imbalance on final assembly",
      "Late transfer confirmations",
      "Manual substitutions on high-runner interiors",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 10", value: 0.79, baseline: 0.84 },
      { label: "Apr 11", value: 0.77, baseline: 0.84 },
      { label: "Apr 12", value: 0.75, baseline: 0.83 },
      { label: "Apr 13", value: 0.73, baseline: 0.83 },
      { label: "Apr 14", value: 0.7, baseline: 0.82 },
    ],
  },
  {
    id: "alert-plant-2-otif-watch",
    severity: "high",
    status: "watch",
    plantId: "plant-2",
    plantName: WARREN,
    metric: "otif",
    title: "Service misses are rising behind Warren line instability",
    summary:
      `${WARREN} began missing the expected outbound release cadence yesterday as maintenance recovery and scrap rework consumed the best ship windows.`,
    detectedAt: "2026-04-14T15:22:00Z",
    changeVsBaseline: -0.05,
    drivers: [
      "Rework carryover into ship window",
      "Late maintenance release",
      "Priority truck-seat expedites",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 10", value: 0.91, baseline: 0.95 },
      { label: "Apr 11", value: 0.9, baseline: 0.95 },
      { label: "Apr 12", value: 0.89, baseline: 0.95 },
      { label: "Apr 13", value: 0.88, baseline: 0.94 },
      { label: "Apr 14", value: 0.87, baseline: 0.94 },
    ],
  },
  {
    id: "alert-plant-3-staging-watch",
    severity: "medium",
    status: "watch",
    plantId: "plant-3",
    plantName: LANSING,
    metric: "otif",
    title: "Outbound staging queues backed up late in second shift",
    summary:
      `${LANSING} kept line output healthy yesterday, but trailer-release handoffs slowed enough to create a visible OTIF watch on a small cluster of outbound orders.`,
    detectedAt: "2026-04-14T13:05:00Z",
    changeVsBaseline: -0.03,
    drivers: [
      "Staging lane congestion",
      "Late packaging confirmation",
      "Shift-end trailer sequencing",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 10", value: 0.94, baseline: 0.96 },
      { label: "Apr 11", value: 0.94, baseline: 0.96 },
      { label: "Apr 12", value: 0.93, baseline: 0.96 },
      { label: "Apr 13", value: 0.93, baseline: 0.95 },
      { label: "Apr 14", value: 0.92, baseline: 0.95 },
    ],
  },
  {
    id: "alert-plant-1-scrap-watch",
    severity: "low",
    status: "watch",
    plantId: "plant-1",
    plantName: OXFORD,
    metric: "scrapRate",
    title: "A brief trim scrap pocket opened on one Oxford product family",
    summary:
      `${OXFORD} stayed healthy yesterday, but one product-family mix change drove a short-lived scrap pocket large enough to keep a low watch in place.`,
    detectedAt: "2026-04-14T11:18:00Z",
    changeVsBaseline: 0.004,
    drivers: [
      "Short-term product mix shift",
      "Operator rotation on trim inspection",
    ],
    sources: ["MES"],
    chartPoints: [
      { label: "Apr 10", value: 0.029, baseline: 0.027 },
      { label: "Apr 11", value: 0.03, baseline: 0.027 },
      { label: "Apr 12", value: 0.031, baseline: 0.027 },
      { label: "Apr 13", value: 0.031, baseline: 0.027 },
      { label: "Apr 14", value: 0.03, baseline: 0.027 },
    ],
  },
  {
    id: "alert-plant-3-scrap-watch",
    severity: "medium",
    status: "resolved",
    plantId: "plant-3",
    plantName: LANSING,
    metric: "scrapRate",
    title: "Lansing surface-finish scrap briefly moved above watch threshold",
    summary:
      `${LANSING} saw a modest surface-finish scrap increase earlier in the week, but the corrective action held and the watch has since been resolved.`,
    detectedAt: "2026-04-12T14:48:00Z",
    changeVsBaseline: 0.003,
    drivers: [
      "Surface-finish variance on one interior family",
      "Verification hold during coating review",
    ],
    sources: ["MES"],
    chartPoints: [
      { label: "Apr 8", value: 0.028, baseline: 0.026 },
      { label: "Apr 9", value: 0.029, baseline: 0.026 },
      { label: "Apr 10", value: 0.03, baseline: 0.026 },
      { label: "Apr 11", value: 0.03, baseline: 0.026 },
      { label: "Apr 12", value: 0.029, baseline: 0.026 },
    ],
  },
  {
    id: "alert-plant-4-otif-watch",
    severity: "high",
    status: "watch",
    plantId: "plant-4",
    plantName: DETROIT,
    metric: "otif",
    title: "Detroit final-assembly orders started missing normal ship timing",
    summary:
      `${DETROIT} mixed-model final assemblies were still shipping, but service timing drifted far enough on April 10 to open a high watch on outbound execution.`,
    detectedAt: "2026-04-10T09:34:00Z",
    changeVsBaseline: -0.05,
    drivers: [
      "Mixed-model sequencing drag",
      "Late transfer approvals",
      "Outbound dock congestion",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 6", value: 0.92, baseline: 0.95 },
      { label: "Apr 7", value: 0.91, baseline: 0.95 },
      { label: "Apr 8", value: 0.9, baseline: 0.95 },
      { label: "Apr 9", value: 0.9, baseline: 0.95 },
      { label: "Apr 10", value: 0.89, baseline: 0.94 },
    ],
  },
  {
    id: "alert-plant-1-material-watch",
    severity: "low",
    status: "watch",
    plantId: "plant-1",
    plantName: OXFORD,
    metric: "inventoryHealth",
    title: "A small material-coverage dip showed up on expedite seat sets",
    summary:
      `${OXFORD} recovered quickly, but a short coverage dip on expedited seat sets was enough to leave a low-severity inventory watch on April 9.`,
    detectedAt: "2026-04-09T07:41:00Z",
    changeVsBaseline: -0.02,
    drivers: [
      "Expedite seat-set pull-forward",
      "Supplier release timing",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Apr 5", value: 0.87, baseline: 0.89 },
      { label: "Apr 6", value: 0.87, baseline: 0.89 },
      { label: "Apr 7", value: 0.86, baseline: 0.89 },
      { label: "Apr 8", value: 0.86, baseline: 0.89 },
      { label: "Apr 9", value: 0.87, baseline: 0.89 },
    ],
  },
  {
    id: "alert-plant-2-foam-critical-resolved",
    severity: "critical",
    status: "resolved",
    plantId: "plant-2",
    plantName: WARREN,
    metric: "inventoryHealth",
    title: "Foam supply exposure briefly escalated into recovery mode",
    summary:
      `${WARREN} nearly exhausted safe foam coverage on one truck-seat family in early April before expedited replenishment and scrap containment stabilized the risk.`,
    detectedAt: "2026-04-04T16:12:00Z",
    changeVsBaseline: -0.11,
    drivers: [
      "Scrap burn on high-volume foam family",
      "Late replenishment release",
      "Manual allocation overrides",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Mar 31", value: 0.77, baseline: 0.84 },
      { label: "Apr 1", value: 0.75, baseline: 0.84 },
      { label: "Apr 2", value: 0.73, baseline: 0.83 },
      { label: "Apr 3", value: 0.71, baseline: 0.83 },
      { label: "Apr 4", value: 0.72, baseline: 0.82 },
    ],
  },
  {
    id: "alert-plant-4-changeover-watch",
    severity: "medium",
    status: "watch",
    plantId: "plant-4",
    plantName: DETROIT,
    metric: "downtime",
    title: "Extended changeovers started stacking on Detroit final assembly",
    summary:
      `${DETROIT} opened a medium watch in early April when extended changeovers and kit substitutions began slowing schedule recovery on the mixed-model line.`,
    detectedAt: "2026-04-03T12:27:00Z",
    changeVsBaseline: 12,
    drivers: [
      "Mixed-model variant sequencing",
      "Late kit substitutions",
      "Supervisor release delays",
    ],
    sources: ["MES", "CMMS"],
    chartPoints: [
      { label: "Mar 30", value: 88, baseline: 80 },
      { label: "Mar 31", value: 90, baseline: 80 },
      { label: "Apr 1", value: 92, baseline: 81 },
      { label: "Apr 2", value: 94, baseline: 81 },
      { label: "Apr 3", value: 93, baseline: 81 },
    ],
  },
  {
    id: "alert-plant-3-outbound-medium",
    severity: "medium",
    status: "resolved",
    plantId: "plant-3",
    plantName: LANSING,
    metric: "otif",
    title: "Late-March outbound verification slowed Lansing trailer release",
    summary:
      `${LANSING} carried a medium OTIF watch in late March when outbound verification delayed trailer release, but the queue has since normalized.`,
    detectedAt: "2026-03-28T18:20:00Z",
    changeVsBaseline: -0.03,
    drivers: [
      "Verification hold queue",
      "Packaging lane congestion",
      "Late outbound signoff",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Mar 24", value: 0.94, baseline: 0.96 },
      { label: "Mar 25", value: 0.93, baseline: 0.96 },
      { label: "Mar 26", value: 0.93, baseline: 0.96 },
      { label: "Mar 27", value: 0.92, baseline: 0.96 },
      { label: "Mar 28", value: 0.92, baseline: 0.95 },
    ],
  },
  {
    id: "alert-plant-2-maintenance-high",
    severity: "high",
    status: "resolved",
    plantId: "plant-2",
    plantName: WARREN,
    metric: "downtime",
    title: "A late-March maintenance backlog pushed Warren above its stop threshold",
    summary:
      `${WARREN} ran a high downtime watch in late March when unplanned tooling work outpaced the maintenance queue, though the specific backlog item has since been closed.`,
    detectedAt: "2026-03-22T10:08:00Z",
    changeVsBaseline: 19,
    drivers: [
      "Tooling maintenance queue backlog",
      "Unplanned trim-fixture replacement",
      "Carryover downtime after quality holds",
    ],
    sources: ["CMMS", "MES"],
    chartPoints: [
      { label: "Mar 18", value: 118, baseline: 103 },
      { label: "Mar 19", value: 121, baseline: 103 },
      { label: "Mar 20", value: 124, baseline: 104 },
      { label: "Mar 21", value: 126, baseline: 104 },
      { label: "Mar 22", value: 123, baseline: 104 },
    ],
  },
  {
    id: "alert-plant-1-otif-low",
    severity: "low",
    status: "resolved",
    plantId: "plant-1",
    plantName: OXFORD,
    metric: "otif",
    title: "Two late-March expedite sets slipped outside Oxford's normal ship window",
    summary:
      `${OXFORD} resolved a small OTIF watch from late March after a pair of expedite seat sets missed the normal outbound release timing.`,
    detectedAt: "2026-03-19T08:40:00Z",
    changeVsBaseline: -0.02,
    drivers: [
      "Short-term expedite mix shift",
      "Outbound coordinator handoff",
    ],
    sources: ["ERP", "MES"],
    chartPoints: [
      { label: "Mar 15", value: 0.95, baseline: 0.96 },
      { label: "Mar 16", value: 0.95, baseline: 0.96 },
      { label: "Mar 17", value: 0.94, baseline: 0.96 },
      { label: "Mar 18", value: 0.94, baseline: 0.96 },
      { label: "Mar 19", value: 0.95, baseline: 0.96 },
    ],
  },
];
