import type {
  DowntimeBucket,
  InventorySignal,
  Plant,
  TimeSeriesPoint,
} from "@/lib/types";

export const PLANTS: Plant[] = [
  {
    id: "plant-1",
    name: "Oxford / Eastaboga, AL",
    region: "Calhoun County, Alabama",
    specialty: "Honda SUV seating programs",
    manager: "Dezi Hamilton",
    aliases: ["oxford", "eastaboga", "alabama", "oxford eastaboga"],
    shiftStatus: "Sequencing is clean, staffing is balanced, and the line is holding cadence.",
    summary:
      "Oxford / Eastaboga is the benchmark Bridgewater facility this week: healthy OEE, low scrap, and very little alert pressure.",
  },
  {
    id: "plant-2",
    name: "Warren, MI",
    region: "Metro Detroit",
    specialty: "Full-size truck seating programs",
    manager: "Johnny Collins",
    aliases: ["warren", "warren michigan", "truck seat build", "truck seating"],
    shiftStatus: "Recovery focus remains on downtime, scrap, and trim availability.",
    summary:
      "Warren is the main risk facility this week due to sustained downtime growth and worsening quality losses across a high-volume seat build.",
  },
  {
    id: "plant-3",
    name: "Lansing, MI",
    region: "Mid-Michigan",
    specialty: "GM interior systems and outbound sequencing",
    manager: "Sheila James",
    aliases: ["lansing", "lansing michigan", "gm interior systems"],
    shiftStatus: "Production remains strong, but outbound service execution needs watch.",
    summary:
      "Lansing remains the strongest producing facility overall, though OTIF has softened enough to warrant sequencing and outbound attention.",
  },
  {
    id: "plant-4",
    name: "Detroit, MI",
    region: "Detroit headquarters campus",
    specialty: "Seating and interior assembly operations",
    manager: "Erik Hall",
    aliases: ["detroit", "detroit michigan", "hq", "headquarters"],
    shiftStatus: "Throughput is steady, but kit balance and transfer timing remain uneven.",
    summary:
      "Detroit is not in crisis, but inventory imbalance is beginning to erode delivery confidence and planner flexibility.",
  },
];

const LABELS = [
  "Apr 2",
  "Apr 3",
  "Apr 4",
  "Apr 5",
  "Apr 6",
  "Apr 7",
  "Apr 8",
  "Apr 9",
  "Apr 10",
  "Apr 11",
  "Apr 12",
  "Apr 13",
  "Apr 14",
  "Apr 15",
];

function buildSeries(
  labels: string[],
  raw: Omit<TimeSeriesPoint, "label">[],
): TimeSeriesPoint[] {
  return raw.map((point, index) => ({
    label: labels[index],
    ...point,
  }));
}

export const PLANT_TIME_SERIES: Record<string, TimeSeriesPoint[]> = {
  "plant-1": buildSeries(LABELS, [
    { oee: 0.79, scrapRate: 0.034, otif: 0.92, inventoryHealth: 0.86, downtime: 87 },
    { oee: 0.8, scrapRate: 0.033, otif: 0.92, inventoryHealth: 0.86, downtime: 85 },
    { oee: 0.81, scrapRate: 0.033, otif: 0.93, inventoryHealth: 0.87, downtime: 82 },
    { oee: 0.8, scrapRate: 0.032, otif: 0.93, inventoryHealth: 0.87, downtime: 84 },
    { oee: 0.81, scrapRate: 0.032, otif: 0.93, inventoryHealth: 0.87, downtime: 80 },
    { oee: 0.82, scrapRate: 0.031, otif: 0.94, inventoryHealth: 0.88, downtime: 78 },
    { oee: 0.82, scrapRate: 0.031, otif: 0.94, inventoryHealth: 0.88, downtime: 76 },
    { oee: 0.81, scrapRate: 0.031, otif: 0.94, inventoryHealth: 0.88, downtime: 79 },
    { oee: 0.82, scrapRate: 0.03, otif: 0.94, inventoryHealth: 0.89, downtime: 75 },
    { oee: 0.83, scrapRate: 0.03, otif: 0.95, inventoryHealth: 0.89, downtime: 72 },
    { oee: 0.82, scrapRate: 0.029, otif: 0.95, inventoryHealth: 0.89, downtime: 74 },
    { oee: 0.83, scrapRate: 0.029, otif: 0.95, inventoryHealth: 0.9, downtime: 70 },
    { oee: 0.84, scrapRate: 0.028, otif: 0.95, inventoryHealth: 0.9, downtime: 68 },
    { oee: 0.84, scrapRate: 0.028, otif: 0.96, inventoryHealth: 0.9, downtime: 69 },
  ]),
  "plant-2": buildSeries(LABELS, [
    { oee: 0.77, scrapRate: 0.041, otif: 0.91, inventoryHealth: 0.82, downtime: 102 },
    { oee: 0.76, scrapRate: 0.042, otif: 0.91, inventoryHealth: 0.82, downtime: 105 },
    { oee: 0.75, scrapRate: 0.043, otif: 0.9, inventoryHealth: 0.81, downtime: 107 },
    { oee: 0.74, scrapRate: 0.044, otif: 0.9, inventoryHealth: 0.81, downtime: 110 },
    { oee: 0.74, scrapRate: 0.045, otif: 0.89, inventoryHealth: 0.8, downtime: 111 },
    { oee: 0.73, scrapRate: 0.046, otif: 0.89, inventoryHealth: 0.8, downtime: 114 },
    { oee: 0.72, scrapRate: 0.047, otif: 0.88, inventoryHealth: 0.79, downtime: 118 },
    { oee: 0.71, scrapRate: 0.048, otif: 0.88, inventoryHealth: 0.79, downtime: 121 },
    { oee: 0.7, scrapRate: 0.049, otif: 0.87, inventoryHealth: 0.79, downtime: 125 },
    { oee: 0.7, scrapRate: 0.05, otif: 0.87, inventoryHealth: 0.78, downtime: 126 },
    { oee: 0.69, scrapRate: 0.051, otif: 0.86, inventoryHealth: 0.78, downtime: 129 },
    { oee: 0.68, scrapRate: 0.053, otif: 0.86, inventoryHealth: 0.77, downtime: 133 },
    { oee: 0.67, scrapRate: 0.054, otif: 0.85, inventoryHealth: 0.77, downtime: 137 },
    { oee: 0.66, scrapRate: 0.056, otif: 0.85, inventoryHealth: 0.76, downtime: 141 },
  ]),
  "plant-3": buildSeries(LABELS, [
    { oee: 0.84, scrapRate: 0.029, otif: 0.95, inventoryHealth: 0.88, downtime: 72 },
    { oee: 0.84, scrapRate: 0.029, otif: 0.95, inventoryHealth: 0.88, downtime: 70 },
    { oee: 0.84, scrapRate: 0.028, otif: 0.95, inventoryHealth: 0.88, downtime: 69 },
    { oee: 0.85, scrapRate: 0.028, otif: 0.94, inventoryHealth: 0.89, downtime: 68 },
    { oee: 0.85, scrapRate: 0.028, otif: 0.94, inventoryHealth: 0.89, downtime: 67 },
    { oee: 0.85, scrapRate: 0.027, otif: 0.94, inventoryHealth: 0.89, downtime: 66 },
    { oee: 0.86, scrapRate: 0.027, otif: 0.93, inventoryHealth: 0.89, downtime: 66 },
    { oee: 0.86, scrapRate: 0.027, otif: 0.93, inventoryHealth: 0.9, downtime: 65 },
    { oee: 0.86, scrapRate: 0.027, otif: 0.93, inventoryHealth: 0.9, downtime: 64 },
    { oee: 0.86, scrapRate: 0.026, otif: 0.92, inventoryHealth: 0.9, downtime: 64 },
    { oee: 0.87, scrapRate: 0.026, otif: 0.92, inventoryHealth: 0.9, downtime: 63 },
    { oee: 0.87, scrapRate: 0.026, otif: 0.91, inventoryHealth: 0.91, downtime: 62 },
    { oee: 0.87, scrapRate: 0.026, otif: 0.91, inventoryHealth: 0.91, downtime: 61 },
    { oee: 0.88, scrapRate: 0.026, otif: 0.9, inventoryHealth: 0.91, downtime: 60 },
  ]),
  "plant-4": buildSeries(LABELS, [
    { oee: 0.8, scrapRate: 0.035, otif: 0.93, inventoryHealth: 0.79, downtime: 91 },
    { oee: 0.8, scrapRate: 0.036, otif: 0.93, inventoryHealth: 0.79, downtime: 89 },
    { oee: 0.79, scrapRate: 0.036, otif: 0.93, inventoryHealth: 0.78, downtime: 92 },
    { oee: 0.79, scrapRate: 0.037, otif: 0.92, inventoryHealth: 0.78, downtime: 90 },
    { oee: 0.8, scrapRate: 0.037, otif: 0.92, inventoryHealth: 0.77, downtime: 92 },
    { oee: 0.8, scrapRate: 0.038, otif: 0.92, inventoryHealth: 0.77, downtime: 94 },
    { oee: 0.79, scrapRate: 0.038, otif: 0.92, inventoryHealth: 0.76, downtime: 95 },
    { oee: 0.79, scrapRate: 0.037, otif: 0.91, inventoryHealth: 0.75, downtime: 93 },
    { oee: 0.8, scrapRate: 0.037, otif: 0.91, inventoryHealth: 0.74, downtime: 96 },
    { oee: 0.8, scrapRate: 0.038, otif: 0.91, inventoryHealth: 0.74, downtime: 95 },
    { oee: 0.81, scrapRate: 0.039, otif: 0.91, inventoryHealth: 0.73, downtime: 97 },
    { oee: 0.81, scrapRate: 0.039, otif: 0.9, inventoryHealth: 0.72, downtime: 98 },
    { oee: 0.8, scrapRate: 0.04, otif: 0.9, inventoryHealth: 0.72, downtime: 96 },
    { oee: 0.8, scrapRate: 0.039, otif: 0.9, inventoryHealth: 0.71, downtime: 97 },
  ]),
};

export const PLANT_DOWNTIME_MIX: Record<string, DowntimeBucket[]> = {
  "plant-1": [
    { category: "Micro Stops", minutes: 118 },
    { category: "Trim Changeover", minutes: 92 },
    { category: "Preventive Maintenance", minutes: 76 },
    { category: "Sequencing Delay", minutes: 52 },
    { category: "Quality Hold", minutes: 38 },
  ],
  "plant-2": [
    { category: "Maintenance", minutes: 231 },
    { category: "Tooling", minutes: 168 },
    { category: "Foam And Trim Delay", minutes: 124 },
    { category: "Changeover", minutes: 112 },
    { category: "Quality Hold", minutes: 97 },
  ],
  "plant-3": [
    { category: "Micro Stops", minutes: 98 },
    { category: "Trailer Staging", minutes: 66 },
    { category: "Packaging Verification", minutes: 58 },
    { category: "Labor Coverage", minutes: 42 },
    { category: "Material Delay", minutes: 39 },
  ],
  "plant-4": [
    { category: "Material Delay", minutes: 146 },
    { category: "Changeover", minutes: 121 },
    { category: "Maintenance", minutes: 103 },
    { category: "Quality Hold", minutes: 74 },
    { category: "Kitting Confirmation", minutes: 61 },
  ],
};

export const PLANT_INVENTORY_SIGNALS: Record<string, InventorySignal[]> = {
  "plant-1": [
    {
      label: "Days Of Supply",
      value: 16,
      target: 14,
      unit: "days",
      narrative: "Seat-kit coverage is comfortable with no immediate JIT stockout pressure.",
    },
    {
      label: "At-Risk Components",
      value: 4,
      target: 6,
      unit: "shipments",
      narrative: "High-risk trim and hardware exposure has stayed below the escalation threshold all week.",
    },
    {
      label: "Planner Confidence",
      value: 88,
      target: 85,
      unit: "%",
      narrative: "Execution confidence remains strong against the current sequencing plan.",
    },
    {
      label: "Supplier Expedites",
      value: 1,
      target: 3,
      unit: "shipments",
      narrative: "Inbound material flow is stable enough that only a single expedite remains open.",
    },
    {
      label: "WIP Balance",
      value: 93,
      target: 88,
      unit: "%",
      narrative: "Work-in-process remains evenly distributed across foam, trim, and final seat assembly cells.",
    },
  ],
  "plant-2": [
    {
      label: "Days Of Supply",
      value: 11,
      target: 14,
      unit: "days",
      narrative: "Coverage is tightening as scrap burns through critical foam and trim inputs.",
    },
    {
      label: "At-Risk Components",
      value: 9,
      target: 6,
      unit: "shipments",
      narrative: "Material churn is starting to affect short-term truck-seat sequencing flexibility.",
    },
    {
      label: "Planner Confidence",
      value: 71,
      target: 85,
      unit: "%",
      narrative: "The build plan is becoming less reliable shift to shift.",
    },
    {
      label: "Supplier Expedites",
      value: 7,
      target: 3,
      unit: "shipments",
      narrative: "Expedite requests are climbing as unstable yield burns through critical trim inputs.",
    },
    {
      label: "WIP Balance",
      value: 68,
      target: 88,
      unit: "%",
      narrative: "Work-in-process is pooling around rework loops and seat hold points instead of flowing cleanly.",
    },
  ],
  "plant-3": [
    {
      label: "Days Of Supply",
      value: 15,
      target: 14,
      unit: "days",
      narrative: "Supply depth is healthy, but outbound sequencing to customer release is softening.",
    },
    {
      label: "At-Risk Components",
      value: 5,
      target: 6,
      unit: "shipments",
      narrative: "Material exposure is moderate and still manageable.",
    },
    {
      label: "Planner Confidence",
      value: 82,
      target: 85,
      unit: "%",
      narrative: "Service risk is more about launch and outbound execution than raw inventory shortfall.",
    },
    {
      label: "Trailer Readiness",
      value: 6,
      target: 4,
      unit: "shipments",
      narrative: "Too many finished interior sets are waiting for trailers and final packaging release at the same time.",
    },
    {
      label: "Finished Goods Staging",
      value: 76,
      target: 88,
      unit: "%",
      narrative: "Finished goods are building faster than the staging lane can clear, which is pressuring OTIF.",
    },
  ],
  "plant-4": [
    {
      label: "Days Of Supply",
      value: 19,
      target: 14,
      unit: "days",
      narrative: "Coverage looks high overall, but it is poorly distributed across key seat and interior kit families.",
    },
    {
      label: "At-Risk Components",
      value: 8,
      target: 6,
      unit: "shipments",
      narrative: "Stock sits in the wrong places, creating localized kit shortages.",
    },
    {
      label: "Planner Confidence",
      value: 74,
      target: 85,
      unit: "%",
      narrative: "Inventory imbalance is reducing confidence in the next two Detroit shifts.",
    },
    {
      label: "Transfer Requests",
      value: 10,
      target: 5,
      unit: "shipments",
      narrative: "Inter-plant transfer requests are stacking up because the right kits are not in the right cells.",
    },
    {
      label: "Kitting Accuracy",
      value: 72,
      target: 88,
      unit: "%",
      narrative: "Kit substitutions and partial kits are increasing line-side disruption during final assembly.",
    },
  ],
};
